export const COMMAND_LIST_REQUEST = 'COMMAND_LIST_REQUEST';
export const COMMAND_LIST_SUCCESS = 'COMMAND_LIST_SUCCESS';
export const COMMAND_LIST_FAIL = 'COMMAND_LIST_FAIL';

export const COMMAND_DETAILS_REQUEST = 'COMMAND_DETAILS_REQUEST';
export const COMMAND_DETAILS_SUCCESS = 'COMMAND_DETAILS_SUCCESS';
export const COMMAND_DETAILS_FAIL = 'COMMAND_DETAILS_FAIL';

export const COMMAND_CREATE_REQUEST = 'COMMAND_CREATE_REQUEST';
export const COMMAND_CREATE_SUCCESS = 'COMMAND_CREATE_SUCCESS';
export const COMMAND_CREATE_FAIL = 'COMMAND_CREATE_FAIL';
export const COMMAND_CREATE_RESET = 'COMMAND_CREATE_RESET';

export const COMMAND_UPDATE_REQUEST = 'COMMAND_UPDATE_REQUEST';
export const COMMAND_UPDATE_SUCCESS = 'COMMAND_UPDATE_SUCCESS';
export const COMMAND_UPDATE_FAIL = 'COMMAND_UPDATE_FAIL';
export const COMMAND_UPDATE_RESET = 'COMMAND_UPDATE_RESET';

export const COMMAND_DELETE_REQUEST = 'COMMAND_DELETE_REQUEST';
export const COMMAND_DELETE_SUCCESS = 'COMMAND_DELETE_SUCCESS';
export const COMMAND_DELETE_FAIL = 'COMMAND_DELETE_FAIL';